Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "private_network", type: "dhcp"
  config.vm.box = "centos/7"

  config.vm.define "mon0" do |mon|
    mon.vm.hostname = "mon0"
  end
  config.vm.define "mon1" do |mon|
    mon.vm.hostname = "mon1"
  end
  config.vm.define "mon2" do |mon|
    mon.vm.hostname = "mon2"
  end

  config.vm.define "mgr0" do |mgr|
    mgr.vm.hostname = "mgr0"
  end
  config.vm.define "mgr1" do |mgr|
    mgr.vm.hostname = "mgr1"
  end
  config.vm.define "mgr2" do |mgr|
    mgr.vm.hostname = "mgr2"
  end

  config.vm.define "osd0" do |osd|
    osd.vm.hostname = "osd0"
    osd.vm.provider :libvirt do |libvirt|
      libvirt.storage :file, :size => '5G'
      libvirt.storage :file, :size => '5G'
    end
  end

  config.vm.define "osd1" do |osd|
    osd.vm.hostname = "osd1"
    osd.vm.provider :libvirt do |libvirt|
      libvirt.storage :file, :size => '5G'
      libvirt.storage :file, :size => '5G'
    end
  end

  config.vm.define "osd2" do |osd|
    osd.vm.hostname = "osd2"
    osd.vm.provider :libvirt do |libvirt|
      libvirt.storage :file, :size => '5G'
      libvirt.storage :file, :size => '5G'
    end
  end

  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = "echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo yum install -y yum-utils
    sudo yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    sudo rpm --import 'https://download.ceph.com/keys/release.asc'
    curl -L https://shaman.ceph.com/api/repos/ceph/master/latest/centos/7/repo/ | sudo tee /etc/yum.repos.d/shaman.repo
    sudo yum install -y ceph python36
    sudo ln -s /usr/bin/python36 /usr/bin/python3
  SHELL
end
