{
 "title": "RGW Sync Overview",
 "tags": [ "overview" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "rgw_servers", "query": "prometheus" },
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Avg. object bytes replicated from source zone",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (source_zone) (rate(ceph_data_sync_from_zone_fetch_bytes_sum[30s]) / rate(ceph_data_sync_from_zone_fetch_bytes_count[30s]))",
     "legendFormat": "{{source_zone}}"
    }
   ]
  },
  {
   "title": "Avg. objects already replicated from source zone",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7.4, "x": 8.3, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Objects/s" }
   ],
   "targets": [
    {
     "expr": "sum by (source_zone) (rate(ceph_data_sync_from_zone_fetch_not_modified[30s]))",
     "legendFormat": "{{source_zone}}"
    }
   ]
  },
  {
   "title": "Avg. latency of replication log requests from source zone",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (source_zone) ((rate(ceph_data_sync_from_zone_poll_latency_sum[30s]) / rate(ceph_data_sync_from_zone_poll_latency_count[30s]) * 1000))",
     "legendFormat": "{{source_zone}}"
    }
   ]
  },
  {
   "title": "Avg. object replication errors from source zone",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Errors/s" }
   ],
   "targets": [
    {
     "expr": "sum by (source_zone) (rate(ceph_data_sync_from_zone_fetch_errors[30s]))",
     "legendFormat": "{{source_zone}}"
    }
   ]
  },
  {
   "title": "Avg. replication log request errors from source zone",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Erros/s" }
   ],
   "targets": [
    {
     "expr": "sum by (source_zone) (rate(ceph_data_sync_from_zone_poll_errors[30s]))",
     "legendFormat": "{{source_zone}}"
    }
   ]
  }
 ]
}